Controllers/MealPlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using Microsoft.AspNetCore.Http;
using MealPlanner.Models;
using MealPlanner.Data;


namespace MealPlanner.Controllers
{
    public class MealPlanController : Controller
    {

        private readonly ApplicationDbContext context;
        public MealPlanController(ApplicationDbContext dbContext)
        {
            context = dbContext;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Pick()
        {

            List<RecipeClass> recipeIndex = context.Recipes.ToList();
            return View(recipeIndex); //TODO Link to all recipes RecipeIndex
        }

        public JsonResult GetMeals()
        {

            int? uid = HttpContext.Session.GetInt32("UID");
            int uid2 = uid.Value;
            
            
            var meals = context.Meals.ToList();
            return new JsonResult (new { Data = meals});   
            

            //return new JsonResult(new { Data = meals });if (uid2 >= 0){}
            
        }

        [HttpPost]
        public JsonResult SaveMeal(MealsClass m)
        {
            var status = false;

            if (m.Id > 0)
            {
                //Update the event
                var v = context.Meals.Where(a => a.Id == m.Id).FirstOrDefault();
                if (v != null)
                {
                    v.MealType = m.MealType;
                    v.Date = m.Date;
                }
            }
            else
            {
                context.Meals.Add(m);
            }
            context.SaveChanges();
            status = true;
            
            return new JsonResult (new{ Data =  status });
        }

        [HttpPost]
        public JsonResult DeleteMeal(int mealId)
        {
            var status = false;
            
            var v = context.Meals.Where(a => a.Id == mealId).FirstOrDefault();
            if (v != null)
            {
                context.Meals.Remove(v);
                context.SaveChanges();
                status = true;
            }
            
            return new JsonResult (new { Data = status  });
        }


        /*public IActionResult ShoppingList()
        {

        }*/
    }
}

Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MealPlanner.Models;
using MealPlanner.Data;
using MealPlanner.ViewModels;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using System.Data;
using Microsoft.AspNetCore.Http;

namespace MealPlanner.Controllers
{
    public class RecipeController : Controller
    {
        //TODO link to the db
        //ApplicationDbContext db = new ApplicationDbContext();
        private readonly ApplicationDbContext context;
        public RecipeController(ApplicationDbContext dbContext)
        {
            context = dbContext;
        }
                       
        //GET: All Recipes
        public IActionResult Index()
        {

            List<RecipeClass> recipeIndex = context.Recipes.ToList();
            return View(recipeIndex); //TODO Link to all recipes RecipeIndex
        }

        
        public IActionResult Add()
        {
            NewRecipeVM addRecipeViewModel = new NewRecipeVM();
            return View(addRecipeViewModel);
        }
        
        //[Authorize] 
        [HttpPost]
        public IActionResult Add(NewRecipeVM obj)
        {
            int? uid = HttpContext.Session.GetInt32("UID");
            int uid2 = uid.Value;

            if (ModelState.IsValid)
            {
                //RecipeClass newRecipe = context.Recipes.Single(c => c.RecId == obj.RecId);
                TagsClass t = new TagsClass
                {
                    TagName = obj.TagName
                };
                context.Tags.Add(t);
                context.SaveChanges();


                RecipeClass r = new RecipeClass
                {
                    RecName = obj.RecName,
                    TagsId = t.Id, 
                    UserId = uid2 
                    //Calories = obj.Calories
                };
                context.Recipes.Add(r);
                context.SaveChanges();
                                            
                             
                InstructionsClass inst = new InstructionsClass
                {   
                    RecipeId = r.Id,
                    StepOrder = obj.StepOrder,
                    Instruct = obj.Instruct
                };
                context.Instructions.Add(inst);
                context.SaveChanges();
                              
                IngredientsClass ing = new IngredientsClass
                { 
                    IngName = obj.IngName,
                    UM = obj.UM
                    //Id = ingQ.Id
                };
                context.Ingredients.Add(ing);
                context.SaveChanges();

                IngQuantClass ingQ = new IngQuantClass
                {
                    RecipeClassId = r.Id,
                    IngredientsClassId = ing.Id,
                    Quantity = obj.Quantity
                    
                };
                context.IngQuant.Add(ingQ);
                context.SaveChanges();

                ViewBag.message = "Recipe created";
                
                return Redirect("/Index");
            }   

            return View(obj);
        }        
    }
}

Views/Recipe/Add.cshtml
@model MealPlanner.ViewModels.NewRecipeVM

@{
    ViewData["Title"] = "Add";
}

<h1>Add</h1>

<h4>NewRecipeVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RecName" class="control-label"></label>
                <input asp-for="RecName" class="form-control" />
                <span asp-validation-for="RecName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IngName" class="control-label"></label>
                <input asp-for="IngName" class="form-control" />
                <span asp-validation-for="IngName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UM" class="control-label"></label>
                <input asp-for="UM" class="form-control" />
                <span asp-validation-for="UM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StepOrder" class="control-label"></label>
                <input asp-for="StepOrder" class="form-control" />
                <span asp-validation-for="StepOrder" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Instruct" class="control-label"></label>
                <input asp-for="Instruct" class="form-control" />
                <span asp-validation-for="Instruct" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TagName" class="control-label"></label>
                <input asp-for="TagName" class="form-control" />
                <span asp-validation-for="TagName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <b>@ViewBag.message</b>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Recipe/Index.cshtml
@model IEnumerable<MealPlanner.Models.RecipeClass>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-controller="MealPlan" asp-action="Index">Meal Plan Calender</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RecName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User.Username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TagsClass.TagName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RecName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TagsClass.TagName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>